syntax = "proto3";

import "google/protobuf/empty.proto";
import "Protos/date.proto";    //Need nuget Google.Api.CommonProtos

option csharp_namespace = "Information";

package app;

service App {
  rpc GetSetting (google.protobuf.Empty) returns (AppSetting);
  rpc GetDictionary(LanguageCode) returns (Dictionary);
}


message AppSetting {
	AppInfo info = 1;
	LanguageCodes languageCodes = 2;
	States states = 3;
	ServiceStatuses serviceStatuses = 4;
}
message AppInfo {
	int32 id = 1;
	string name = 2;
	google.type.Date installOn = 3;
	string version = 4;
	string license = 5;
}
message LanguageCode{
	string code = 1;
	string name = 2;
}
message LanguageCodes{
	repeated LanguageCode values = 1;
}
message State{
	int32 id =1;
	string code = 2;
}
message States{
	repeated State values = 1;
}
message ServiceStatus{
	int32 id = 1;
	int32 nextStatusId = 2;
	string code = 3;
}
message ServiceStatuses{
	repeated ServiceStatus values = 1;
}
message DictionaryEntry{
	string key = 1;	
	string value = 2;
}
message Dictionary{
	app.LanguageCode languageCode = 1;
	repeated DictionaryEntry entries = 2;
}
message Dictionaries{
	repeated Dictionary collection = 1;
}